### ISSUE TITLE
Failed to serialize response

### ISSUE THREAD

**Issue by Gahui** [cochlearai/sense-client#4]
안녕하세요.
wav 파일 (16kHz)로  age_gender를 test 중인데
아래와 같은 에러가 발생할 때가 있고, 아닐 때가 있습니다.

어떤 것을 확인해보아야 할 지 문의 드려요.

Traceback (most recent call last):
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.INTERNAL
	details = "Failed to serialize response!"
	debug_error_string = "{"created":"@1543213094.504991673","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1017,"grpc_message":"Failed to serialize response!","grpc_status":13}"

**Comment by Deepakdubey90** [comment]
Hi , I'm also having same issue. any help?
 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/deepakdubey/datalab-gbiml/gbiml-client/gbiml_client/core/grpc_api.py", line 110, in stop_model
    responses = _MODEL_SERVICE_CLIENT.StopModel(request)
  File "/Users/deepakdubey/datalab-gbiml/env/lib/python3.6/site-packages/grpc/_channel.py", line 532, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/deepakdubey/datalab-gbiml/env/lib/python3.6/site-packages/grpc/_channel.py", line 466, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.INTERNAL
	details = "Failed to serialize response!"
	debug_error_string = "{"created":"@1549879267.871434000","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1099,"grpc_message":"Failed to serialize response!","grpc_status":13}"
```

**Comment by leesoup87** [comment]
Maybe many reasons can cause "grpc_status:13". It is internal error that don't contain right response information as expected type.

But usually, If some requests have wrong format of audio file or sending some audio file which API's backend can't decode, both can make failed deserialized response message.
If every call you made have same problem, we recommend that check client's environment first. 

Our new version of API will be on July and it will be more scalable and easy to use!

Thanks!
